### ISSUE TITLE
GCN Waluigi Stadium T miscalculated glider suggestion.

### ISSUE THREAD

**Issue by jayhawx** [MKT-Playbook/Hub#38]
It's recommending a level 1 glider over my level 5 or 6 options. It's also not even showing my Level 6 Waluigi Wing

![image](https://github.com/MKT-Playbook/Hub/assets/134079621/890c0f2a-eeb5-4e95-b9c1-9650fe7b83be)

![image](https://github.com/MKT-Playbook/Hub/assets/134079621/ce8d803a-9e9c-417e-a3e8-ef6ee1aac484)

**Smartphone:**
 - Device: iPhone13 Pro Max
 - OS: iOS 16.4.1(a)
 - Jailbroken: NO

**Comment by TitusPosiadly** [comment]
Hey, thanks for the report.

The level doesn't really affect the score on second and third-shelf cards, because the bonus points gained by higher-level cards only apply to top-shelf cards. That's why for second and third-shelf cards usually only the points and skills are important. You can imagine it like every second and third-shelf card is level 1 in regards to the score.

Even though this might seem like an error at first, it is actually the correct prediction in this case.

I'm gonna close this issue for now, but let me know if you still think something's not right here.

**Comment by jayhawx** [comment]
Ok thanks for the clarification! I love your app! Thanks!
