### ISSUE TITLE
Cointracker issues

### ISSUE THREAD

**Issue by dredlich1** [MKT-Playbook/Hub#44]
Hi! 

After daylight savings, I noticed that the coin tracker did not reset at the right time anymore. For me, the daily reset used to be at 1 am, and after daylight savings it changed to 12:00 am. The coin tracker still resets at 1 am.

Second: after this newest tour, the coin tracker seems to not have reset, even at 1 am. I have included a screenshot: 
![IMG_1492](https://github.com/MKT-Playbook/Hub/assets/61759717/ec32eb19-9447-402e-b271-3764152e30ae)

Thanks!

**Comment by TitusPosiadly** [comment]
Hey, and thanks for the issue report.

Yeah... Daylight savings is a fun time every year. I tried to fix this multiple times before, but because I can only test it once/twice a year and because daylight savings is different in every country it's really hard to diagnose. I think I added a self-fixing function somewhere which should get everything back to working on the second day of the tour. It would be a huge help if you could keep an eye on it and tell me if it still doesn't reset in a day or two or if everything works from that point onwards. Also, if you are willing to share, what country are you in so I know which daylight saving this affects/which day this started?

Cheers and thanks again for helping out.

**Comment by dredlich1** [comment]
Hey! Sorry for the delayed response.

I am stationed in the US, and the coin tracker has still not reset since I reported it. Something probably went wrong when transitioning to the new tour that made the tracker stuck. 

Thanks!

**Comment by TitusPosiadly** [comment]
Hey, thanks for getting back to me. 

So I had a look again at the code. And based on your screenshot it does seem like the coin tracker did reset, but only partly. All the previous transactions got deleted (just as they should have after each tour) but the coins that get reset daily did not. You should be able to fix this by adding a simple transaction of adding 0 coins and the coin tracker should reset the coin count the next day. 

Let me know if that fixes it. Or if there were more things that didn't reset and that I might have missed.

**Comment by dredlich1** [comment]
It worked! The coins reset to 0 and at the correct time. Thank you!
