### ISSUE TITLE
Wario's Shipyard R incorrect number of item boxes

### ISSUE THREAD

**Issue by dtra** [MKT-Playbook/Hub#7]
Says 8 item boxes, but there are only 6 item boxes (unless using extra box strategy).

**Comment by TitusPosiadly** [comment]
Yeah, I was referring to the extra box strategy. The stats are mainly for the score calculator, that's why I decided to add the two extra item boxes to increase the possible score. The stats are from way back when the track was first introduced though, so it might not be the best strategy anymore with the current bot AI. What would you say? Is that still a valid strategy?

**Comment by dtra** [comment]
Ahh ok, that makes sense, I dunno, for coinbox I wouldn’t use the extra box strategy, but better players than I definitely would, for lucky 7 I definitely would use the extra box strategy on this track, The estimate for my 7-3/7-3/7-3 loadout still seems a bit high, 256 actions, but I suppose with the extra item boxes it could be doable, score seems high though, 60k

**Comment by dtra82** [comment]
Updated score estimate is 👌

**Comment by kdurov** [comment]
It should be 10 item boxes if you take extra vox strat into consideration.

**Comment by TitusPosiadly** [comment]
Is the est. score too low for you now? If so, maybe the middle of 9 item boxes would be a good compromise. Meaning one would do the extra box strat only on the first lap.
